create or replace 
PROCEDURE 
	PROC_NEW_CUSTOMER (CUSTOMER_ID OUT INTEGER,
					  FIRST_NAME IN VARCHAR2,
					  BALANCE IN OUT NUMBER
					 ) IS
BEGIN
	SELECT SEQ_CUSTOMER_ID.nextval INTO CUSTOMER_ID
	FROM dual;

	IF BALANCE IS NULL THEN
		SELECT 100 INTO BALANCE
		FROM dual;
	END IF;
	
	INSERT INTO CUSTOMER 
	VALUES (CUSTOMER_ID, FIRST_NAME,BALANCE);
END PROC_NEW_CUSTOMER;
	
					  